language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: GITHUBTOKEN
  keep_history: false
  local_dir: docs
  target_branch: gh-pages
  email: frontend@kpn.com
  verbose: true
  on:
    branch: master
