language: node_js
node_js:
  - "12.13.0"
script:
  - echo "Skipping tests"
  - npm run build
  - echo "style.kpn.com" >> CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUBTOKEN
  keep_history: false
  local_dir: docs
  target_branch: gh-pages
  email: frontend@kpn.com
  verbose: true
  on:
    branch: master
